- index.js
- package.json
- test/test.js
This is a work in progress. Not to be merged as is....
To decide:
- pass through change in API such that success callback signature changes? If so, a breaking change notice and docs update are in order
- does this work with the multitude of options combinations possible?
> WIP: update to node-sass version 2 beta

- index.js
This PR fixes an undefined `sourceMap` variable. 
Fixes https://github.com/dlmanning/gulp-sass/issues/166.
> Fix success callback check for generated sourcemap

- index.js
This PR improves the emitted error by (re)adding useful properties.
In `gulp-sass@1.3.2` / `node-sass@2.0.0-beta` the error message format has changed; instead of including the line number & file as part of the `err.message` string, an object is returned.
I see that the `errLogToConsole` method has been updated (https://github.com/dlmanning/gulp-sass/commit/55601e217b5bb579c825ad4089c19767e84c046e) to re-add the line & file properties but the errors emitted into the stream with `return cb(new gutil.PluginError('gulp-sass', err))` ([index.js#L73](https://github.com/dlmanning/gulp-sass/blob/master/index.js#L73)) are missing the line number & file name as the only properties `gutil.PluginError` preserves are `'name', 'message', 'fileName', 'lineNumber', 'stack', 'showStack', …
> Add lineNumber & fileName to emitted error

- README.md
npm is stricter about Markdown than GitHub and doesn't like when you omit a space between the hash and the heading
> Fix markdown h1 formatting in readme

- index.js
Makes it more obvious that an error has occurred, similar to how Ruby Sass handles errors during compilation.
Also removed the `+`'s, cleaner with separate arguments, `gutil.log()` will format it correctly.
> Format `errLogToConsole` message with red color

- index.js
- package.json
At least the test still pass and paths looks the same with and without the relative fudge.
Sourcemaps are completely wonky though and do not point at the right thing
Also removes jshint since it's using eslint now
> Sourcemap paths seem to be relative now?

- index.js
- test/main.js
Reroll of #225
* Passes file as data instead of passing file name
* Updates error message handling to show real file name instead of `stdin`
* Reimplements `includePaths` handling so we can pass file data directly
* Massages source maps to replace `stdin` and `stdout` with the right file names
* Resolves #158, #202
Do we think we should have tests specifically for the issues going on in there? I've done some basic tests to determine if it works, but nothing more in-depth.
> 2.x datastream

- index.js
This will let you write `require('gulp-sass').compiler.types`, for example, and access
the new `node-sass` [types](https://github.com/sass/node-sass#typesnumbervalue--unit--) without having to `require('node-sass')` in your own code.
Additionally, this lets you use a forked compiler, or a different branch
of the same compiler, by overriding `require('gulp-sass').compiler`.
What do you think?
> Allow you to change the compiler and expose it

- CHANGELOG.md
- CONTRIBUTING.md
Adds contributing guidelines to the project. Heavily inspired by Atom's contributing guidelines. We can have a discussion about content, but I think it's important we get these in before 2.0
> Add Contributing Guidelines

- index.js
- package.json
- test/main.js
As described in [the comments of issue 106](https://github.com/dlmanning/gulp-sass/issues/106#issuecomment-100314779), I'm receiving an incomplete `sources` property when feeding the results from `gulp-sass` into `autoprefixer` (using `gulp-postcss` or `gulp-autoprefixer`). This was not the case in earlier versions of this plugin. As [suggested](https://github.com/dlmanning/gulp-sass/issues/106#issuecomment-100391439) by @w0rm, changing the file extension of the map's `file` property fixes the issue and the existing tests still succeed.
> Fix issue with sourcemaps when using gulp-sourcemaps and autoprefixer

- index.js
If the current file's path is placed at the end, it will be the last folder to check for imports. Which I feel is incorrect.
> Unshift instead of push current file's path onto includePaths.

- index.js
This should solve https://github.com/dlmanning/gulp-sass/pull/257:
The original error is thrown but its message is extended to include file and line. Additionally, a color formatted version is provided to `logError`.
> Error handling: Throw complete sass error but extend message

- index.js
Fixes #90. Related to: https://github.com/gulpjs/gulp/issues/259
I think recommending people to not `return` the gulp stream is not a good idea, because gulp will not know when the task is complete, therefore any tasks that depend on sass being done will not be guaranteed that (think race conditions).
> Fix gulp watch stopping on error.

- index.js
- test/main.js
Hi! Use sass and autoprefixer together on work. Need to fix ASAP.
Thanks!
> Fixed sourcemaps with different file.base

- index.js
- test/main.js
Modify sourcemap paths of imported files relative to file.base instead of relative to file, if a different base is specified. Resolves #319
> Modify sourcemap paths of imported files

- package.json
- test/main.js
We've started releasing the [LibSass 3.3.0 betas](https://github.com/sass/libsass/releases/tag/3.3.0-beta1). In order to truly beta test LibSass 3.3.0 we real users to have the option to use it. Unfortunately due to the nature of LibSass being a library, the majority of our users come from node-sass via Grunt/Gulp Sass.
Node sass has start releasing their [v3.4.0 betas](https://github.com/sass/node-sass/releases/tag/v3.4.0-beta1) which enables the new LibSass betas.
We'd like for gulp-sass to release a 2.1.0 beta with an updated `node-sass@^v3.4.0-beta1` dependency so gulp-sass users can opt into beta testing LibSass 3.3.0. Using this version string means users _should_ be opted into all Node Sass 3.4.0 betas. 
Once Node Sass 3.4.0 is stable, Gulp Sass 2.1.0 stable can be released with …
> Use node-sass@3.4.0-beta

- index.js
- package.json
- test/main.js
This PR updates to the stable node-sass@^3.4.0.
It also updates the error messages to use LibSass pre-formatted errors. This means gulp-sass will now produce the exact same error messages as LibSass, node-sass, and grunt-sass.
**Before**
```
test/scss/error.scss
property "font" must be followed by a ':'
```
**After**
```
test/scss/error.scss
Error: property "font" must be followed by a ':'
on line 2 of stdin
>>   font 'Comic Sans';
--^
```
> Node Sass 3.4.0

- package.json
- test/main.js
We don't remove generated files between tests which results in
false positives when asserting if a file was created. This was
noticed when creating the test cases for #358
> Test runner should clean up after itself

- index.js
- test/main.js
Currently if the input file is blank we bail out early, returning
the input file object. This causes gulp to simply copy the input
Sass file. We instead need to rewrite the file extension to .css.
Fixes #352
> An empty Sass file should produce an empty CSS file

- .eslintrc
- index.js
- package.json
Some of our dependencies are at least a major version behind.
This require update required updating our `.eslintrc` config because
some of the rules we used have been removed.
> Update npm dependencies

- package.json
Following on from https://github.com/dlmanning/gulp-sass/pull/360.
PostCSS >= 6.0.0 has dropped support for Node 0.10. Whether we want to follow suit is beyond my pay grade here :)
> Update PostCSS deps the latest versions that support 0.10

- index.js
Fixed the issue where sourcemaps were not displaying the correct filename, but were instead displaying 'stdin'
> Fixed sourcemaps filename issue ('stdin')

- index.js
- test/main.js
This would particularly be useful for use with `gulp-notify`.
I've also added a corresponding assertions to the respective "should handle sass errors" tests.
> add relativePath property to error object for notification(s) support

- index.js
- test/main.js
This would particularly be useful for use with gulp-notify.
see #399 and #417
> preserve the original error message for notification(s) support

- test/main.js
It looks like a dependency has caused some tests to start failing.
Sourcemaps are not a documented API so this is not a breaking
change.
> Fix failing sourcemaps tests

- index.js
This sets the `file` property on the options object that gets passed along to node-sass.
This is important for using [`eyeglass`](https://github.com/sass-eyeglass/eyeglass) modules. `eyeglass` uses a custom importer and without knowing the file path origin, it isn't able to do it's job correctly.
Note that this doesn't really change how node-sass is going to render the file as `data` still takes precedence over `file`. This is just preserving the origin of the file.
Related issues:
https://github.com/sass-eyeglass/eyeglass/issues/64
https://github.com/sass-eyeglass/eyeglass/issues/42
Fixes #324
/cc @chriseppstein
> add the .file property to options before handing off to node-sass

- index.js
I believe this was mistakenly removed in #353.
@eoneill can you shed some light on why you removed this? It has
caused issues for users.
Fixes #469
Fixes #473
> Restore includePaths logic

- index.js
- package.json
Currently options are leaking between compilation runs. This is most
evident when using an array of importers. The array is shallow copied
internally, and the children of that array are wrapped by Node Sass.
When the next file is compiled the options are shallow copied once
again however this time the importer array contains the wrapped
importers not the original ones.
Instead of shallow copying with `Object.assign` this patch does a
full deep clone. Node Sass should also do this to prevent mutating
the options being passed in.
Related sass/node-sass#1168
Fixes #467 (probably)
> Prevent options leaking between compilations

- index.js
- test/main.js
> Declaring logError as function instead of arrow function.

- README.md
It's not clearly documented how to add options to sass.sync, and this is implemented inconsistently across other code infrastructures, so it's not safe to assume whether it's `sass(options).sync()` or `sass.sync(options)` please accept the pull request if the proposed documentation is correct, or otherwise accept it anyways and provide a follow up merge as an update fix.
> Add documentation for synchronous code options

- index.js
- package.json
The modularized lodash packages are unmaintained since 2 years, lagging a lot behind the main lodash package. Partial imports of lodash are the preferred way.
See https://github.com/lodash/lodash/issues/2969
> Migrate to the lodash package

- CHANGELOG.md
- package.json
Synk analysis flags lodash as having a security issue around
prototype pollution. This upgrades to the first version
that fixes this issue.
Resolves: https://github.com/dlmanning/gulp-sass/issues/775
Relates to: https://app.snyk.io/vuln/SNYK-JS-LODASH-567746
Relates to: https://app.snyk.io/vuln/SNYK-JS-LODASH-590103
Relates to: https://app.snyk.io/vuln/SNYK-JS-LODASH-608086
Relates to: https://app.snyk.io/vuln/SNYK-JS-LODASH-450202
Relates to: https://app.snyk.io/vuln/SNYK-JS-LODASH-73638
Relates to: https://app.snyk.io/vuln/SNYK-JS-LODASH-73639
> Upgrade lodash to fix a security issue

- README.md
Someone asked in #802 if `gulp-sass` could be imported as an ESM module. The answer is yes, and hopefully these edits provide some clarity.
> Document usage in ESM modules

- index.js
- package-lock.json
- package.json
Notes:
1. lodash isn't in any of the current dependencies' deps
2. I'm unsure if the individual packages are still maintained, though. Alternatively, we could find another package.
https://packagephobia.com/result?p=lodash%2Clodash.clonedeep
> Replace lodash with the lodash.clonedeep package

- index.js
- test/main.js
* use `String.startsWith`
* use `String.includes`
> Minor lint tweaks

- index.js
- package-lock.json
- package.json
Inspired by #828.
Rationale: postcss is already using picocolors itself and it's smaller and faster (compared to chalk 4.x, v5 is ESM only).
> Replace chalk with picocolors

- package-lock.json
- package.json
- test/expected-sass/indent.css
- test/expected-sass/inheritance.css
- test/expected-sass/mixins.css
- test/expected-sass/variables.css
- test/main.js
- test/scss/includes/_dogs.sass
@xzyfer I think it's worth having this. That being said, I noticed a few differences while working on this patch. This one makes me wonder:
https://github.com/dlmanning/gulp-sass/pull/842/files#diff-5a684c173d69bcc8d9e0e4b50ac83d8eaf640dbd8e141c14d9e1a953c87afbd3R482
> Add sass tests too

- CHANGELOG.md
- README.md
- legacy.js
- package-lock.json
- package.json
- test/main.js
The legacy render API will be removed in sass 2.0. Keep the legacy API as an option, but default to the new API to encourage adoption.
Add `sass-embedded` in tests and update assertions to support the results from v2 of the JS API.
Fixes #837
> Migrate to use the new Sass JS API by default
